# Generated by Django 3.1.4 on 2022-02-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascot', '0002_auto_20220214_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotBanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main_usd_bank', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
