# Generated by Django 3.1.4 on 2022-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascot', '0004_mascotplayerbanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('with bonus', 'with bonus'), ('only bonus', 'only bonus'), ('without bonus', 'without bonus')], max_length=20)),
            ],
        ),
    ]
