# Generated by Django 3.1.4 on 2022-03-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascot', '0006_mascotsessions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotbalancelog',
            name='bonus_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mascotbalancelog',
            name='real_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
