# Generated by Django 3.1.4 on 2021-05-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='deposit',
            field=models.FloatField(default=0),
        ),
    ]
