# Generated by Django 3.1.4 on 2021-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
    ]
