# Generated by Django 3.1.4 on 2021-06-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_usergametoken_active'),
        ('payments', '0001_initial'),
        ('accounts', '0005_auto_20210615_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=500)),
                ('is_crypto', models.BooleanField(default=False)),
                ('divider', models.FloatField(default=1)),
                ('is_main', models.BooleanField(default=False)),
                ('parent_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('bonus_balance', models.FloatField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4)),
                ('initial_amount', models.FloatField()),
                ('amount', models.FloatField()),
                ('transaction_start_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_end_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('bet', 'bet'), ('win', 'win'), ('refund', 'refund'), ('bonus_bet', 'bonus_bet'), ('bonus_win', 'bonus_win')], max_length=100)),
                ('transaction_status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('deleted', 'deleted')], max_length=100)),
                ('transaction_order_number', models.CharField(blank=True, max_length=200, null=True)),
                ('game_round', models.UUIDField(blank=True, null=True)),
                ('game_transaction_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.currency')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
                ('payment_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_from', to='accounts.currency')),
                ('currency_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_to', to='accounts.currency')),
            ],
        ),
    ]
