# Generated by Django 3.1.4 on 2021-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_currency_rate_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
