# Generated by Django 3.1.4 on 2021-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210630_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('bet', 'bet'), ('win', 'win'), ('refund', 'refund'), ('bonus_bet', 'bonus_bet'), ('bonus_win', 'bonus_win'), ('reset', 'reset')], max_length=100),
        ),
    ]
