# Generated by Django 3.1.4 on 2021-08-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210723_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='game_round',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
