# Generated by Django 3.1.4 on 2021-08-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210815_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='deposit',
        ),
    ]
