# Generated by Django 3.1.4 on 2021-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_useraccount_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='identification_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_pep',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
