# Generated by Django 3.1.4 on 2021-09-16 16:51

import accounts.services.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210914_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='identification_document_1',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.services.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='identification_document_2',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.services.utils.path_and_rename),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'unverified'), ('pending', 'pending'), ('verified', 'verified'), ('rejected', 'rejected')], default='unverified', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
    ]
