# Generated by Django 3.1.4 on 2021-10-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210916_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='BTC_TO_USD',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ETH_TO_USD',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('deposit_exchange', 'deposit_exchange'), ('withdrawal', 'withdrawal'), ('bet', 'bet'), ('win', 'win'), ('refund', 'refund'), ('bonus_bet', 'bonus_bet'), ('bonus_win', 'bonus_win'), ('reset', 'reset'), ('rollback', 'rollback')], max_length=100),
        ),
    ]
