# Generated by Django 3.1.4 on 2021-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211004_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('deposit_exchange', 'deposit_exchange'), ('withdrawal', 'withdrawal'), ('withdrawal_exchange', 'withdrawal_exchange'), ('bet', 'bet'), ('win', 'win'), ('refund', 'refund'), ('bonus_bet', 'bonus_bet'), ('bonus_win', 'bonus_win'), ('reset', 'reset'), ('rollback', 'rollback')], max_length=100),
        ),
    ]
