# Generated by Django 3.1.4 on 2021-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211019_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'pending'), ('manual_confirmation', 'manual_confirmation'), ('waiting_for_provider_confirmation', 'waiting_for_provider_confirmation'), ('success', 'success'), ('deleted', 'deleted')], max_length=100),
        ),
    ]
