# Generated by Django 3.1.4 on 2021-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211019_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
