# Generated by Django 3.1.4 on 2021-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211019_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='registered_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
