# Generated by Django 3.1.4 on 2021-11-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_transaction_transaction_token'),
        ('accounts', '0018_useraccount_registered_at'),
    ]

    operations = [
    ]
