# Generated by Django 3.1.4 on 2021-11-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20211111_0849'),
        ('accounts', '0018_auto_20211104_1457'),
    ]

    operations = [
    ]
