# Generated by Django 3.1.4 on 2021-11-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20211111_0904'),
        ('accounts', '0019_merge_20211110_1516'),
    ]

    operations = [
    ]
