# Generated by Django 3.1.4 on 2021-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20211113_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
