# Generated by Django 3.1.4 on 2021-12-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211121_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount_wagered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bonus_bet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bonus_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
