# Generated by Django 3.1.4 on 2021-12-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20211219_2259'),
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bonus_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonus.bonus'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('deposit_exchange', 'deposit_exchange'), ('withdrawal', 'withdrawal'), ('withdrawal_exchange', 'withdrawal_exchange'), ('bet', 'bet'), ('win', 'win'), ('reset', 'reset'), ('rollback', 'rollback'), ('bonus_bet', 'bonus_bet'), ('bonus_win', 'bonus_win'), ('bonus_reset', 'bonus_reset'), ('bonus_rollback', 'bonus_rollback'), ('refund', 'refund')], max_length=100),
        ),
    ]
