# Generated by Django 3.1.4 on 2022-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20211219_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='logged_out',
            field=models.BooleanField(default=False),
        ),
    ]
