# Generated by Django 3.1.4 on 2022-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_useraccount_logged_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
