# Generated by Django 3.1.4 on 2022-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20220105_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='currency_to_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
