# Generated by Django 3.1.4 on 2022-01-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20220120_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
