# Generated by Django 3.1.4 on 2022-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_wallet_free_spin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='identification_document_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='identification_document_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
