# Generated by Django 3.1.4 on 2022-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20220329_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='notify_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
