version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/core:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - core_network
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=poker
    networks:
      - core_network

  redis_container_core:
    image: redis
    ports:
      - "6378:6379"
    networks:
      - core_network
    restart: always
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/core
    command: celery -A config.settings worker -B -l INFO
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/core:/usr/src/app/
    networks:
      - core_network
    depends_on:
      - backend
      - redis_container_core
      - db

volumes:
  postgres_data:

networks:
  core_network:
    name: mima_network
