# Generated by Django 3.1.4 on 2021-12-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0008_auto_20211116_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('wager_number', models.IntegerField()),
                ('active_from', models.DateTimeField()),
                ('active_to', models.DateTimeField()),
                ('expiration_time_days', models.IntegerField()),
                ('is_deposit_bonus', models.BooleanField(default=False)),
                ('deposit_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
            ],
        ),
    ]
