# Generated by Django 3.1.4 on 2021-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField()),
                ('report_to', models.DateTimeField()),
                ('registrations', models.IntegerField(default=0)),
                ('players', models.IntegerField(default=0)),
                ('depositors', models.IntegerField(default=0)),
                ('fiat_deposits', models.FloatField(default=0)),
                ('crypto_deposits', models.FloatField(default=0)),
                ('total_deposits', models.FloatField(default=0)),
                ('average_deposits', models.FloatField(default=0)),
                ('real_balance_total', models.FloatField(default=0)),
                ('bonus_balance_total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
