# Generated by Django 3.1.4 on 2021-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210810_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='base_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
