# Generated by Django 3.1.4 on 2021-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_cover_images'),
        ),
    ]
