# Generated by Django 3.1.4 on 2021-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_ante',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='min_ante',
            field=models.FloatField(default=1),
        ),
    ]
