# Generated by Django 3.1.4 on 2022-02-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20220210_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_url', models.CharField(max_length=200)),
            ],
        ),
    ]
