# Generated by Django 3.1.4 on 2022-02-17 11:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gameprovider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gameprovider',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
