# Generated by Django 3.1.4 on 2022-02-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20220217_1105'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gameprovider',
            managers=[
            ],
        ),
    ]
