# Generated by Django 3.1.4 on 2022-02-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20220217_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='provider_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gameprovider'),
        ),
    ]
