# Generated by Django 3.1.4 on 2022-03-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='played_time',
            field=models.IntegerField(default=0),
        ),
    ]
