# Generated by Django 3.1.4 on 2022-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_usergamelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='game_cover_images_mobile'),
        ),
    ]
