# Generated by Django 3.1.4 on 2022-04-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_game_cover_image_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='get_round_detail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
