# Generated by Django 3.1.4 on 2021-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('website', models.URLField(blank=True, null=True)),
                ('merchant_number', models.CharField(blank=True, max_length=250, null=True)),
                ('gateway_number', models.CharField(blank=True, max_length=250, null=True)),
                ('testing', models.BooleanField(default=True)),
                ('test_sign_key', models.CharField(blank=True, max_length=250, null=True)),
                ('test_endpoing', models.URLField(blank=True, null=True)),
                ('prod_sign_key', models.CharField(blank=True, max_length=250, null=True)),
                ('prod_endpoint', models.URLField(blank=True, null=True)),
                ('min_deposit', models.FloatField(blank=True, null=True)),
                ('max_deposit', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
