# Generated by Django 3.1.4 on 2021-06-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentprovider',
            old_name='test_endpoing',
            new_name='test_endpoint',
        ),
    ]
