# Generated by Django 3.1.4 on 2021-11-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentprovider_test_merchants_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentprovider',
            old_name='test_merchants_number',
            new_name='test_merchant_number',
        ),
    ]
