# Generated by Django 3.1.4 on 2021-12-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20211104_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='is_crypto',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='regions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
